username: admin
password: admin
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  ceos:
    address: ceos:6030

subscriptions:
  srl-mac-table:
    mode: stream
    stream-mode: on-change
    paths:
      - /network-instance[name=lanswitch]/bridge-table/mac-table/mac[address=*]

outputs:
  file_output:
    type: file
    filename: /data/mac_updates.json
    format: json
    split-events: true
