username: admin
password: admin
insecure: true
encoding: json_ietf
timeout: 10s

targets:
  ceos:
    address: ceos:6030

subscriptions:
  eos-mac-table:
    mode: stream
    stream-mode: on-change
    origin: eos-native
    paths:
      - /Smash/bridging/status/smashFdbStatus

outputs:
  file_output:
    type: file
    filename: /data/mac_updates.json
    format: json
    split-events: true
