username: admin
password: admin
insecure: true
timeout: 10s

targets:
  ceos:
    address: ceos:6030

subscriptions:
  eos-system-performance:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - eos_native:/Kernel/proc/cpu/utilization/total

outputs:
  
  prom-output:
    type: prometheus
    listen: :9273        
